CREATE TABLE Usuario (
    Username VARCHAR(55) NOT NULL 
		CONSTRAINT USUARIO_IDUSUARIO_PK PRIMARY KEY,
    NombreUsr VARCHAR(55) NOT NULL,
    AperllidoUsr VARCHAR(55) NOT NULL,
    CorreoUsr VARCHAR(55) NOT NULL,
    ContraseñaUsr VARCHAR(16) NOT NULL,
    TelefonoUsr CHAR(12) 
		CONSTRAINT USUARIO_TELEFONO_CK CHECK (TelefonoUsr ~ '^5076\d{3}-\d{4}$')
);

CREATE TABLE TipoLocal (
    ID_TipoLocal SERIAL NOT NULL 
		CONSTRAINT TIPOLOCAL_ID_TIPOLOCAL_PK PRIMARY KEY,
    Nombre_Tipo VARCHAR(20) NOT NULL
);

CREATE TABLE Provincia (
    ID_Provincia INT NOT NULL 
		CONSTRAINT PROVINCIA_ID_PROVINCIA_PK PRIMARY KEY,
    Nombre_Provincia VARCHAR(30) NOT NULL
);

CREATE TABLE Lugar (
    ID_Lugar SERIAL NOT NULL 
		CONSTRAINT LUGAR_ID_LUGAR_PK PRIMARY KEY,
    Nombre_Lugar VARCHAR(55) NOT NULL,
    Direccion_Lugar VARCHAR(75) NOT NULL,
    Descripcion VARCHAR(250),
    Lugar_img VARCHAR(255),
    ID_Provincia INT NOT NULL 
		CONSTRAINT LUGAR_ID_PROVINCIA_FK 
        	REFERENCES Provincia(ID_Provincia) ON DELETE CASCADE ON UPDATE CASCADE,
    ID_TipoLocal INT NOT NULL 
		CONSTRAINT LUGAR_ID_TipoLocal_FK 
        	REFERENCES TipoLocal(ID_TipoLocal) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Reseña (
    ID_Reseña SERIAL NOT NULL 
		CONSTRAINT RESEÑA_ID_RESEÑA_PK PRIMARY KEY,
    Puntuación INT NOT NULL,
    Comentario TEXT,
    Fecha DATE,
    ImagenURL VARCHAR(255),
    Username VARCHAR(55)
		CONSTRAINT RESEÑA_USERNAME_FK 
			REFERENCES Usuario(Username) ON DELETE CASCADE ON UPDATE CASCADE,
    ID_Lugar INT
		CONSTRAINT RESEÑA_ID_LUGAR_FK 
			REFERENCES Lugar(ID_Lugar) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Artículo (
    ID_Artículo SERIAL NOT NULL 
		CONSTRAINT ARTICULO_ID_ARTICULO_PK PRIMARY KEY,
    Nombre VARCHAR(55) NOT NULL,
    Descripción TEXT,
    Precio DECIMAL(10, 2) NOT NULL CHECK (Precio >= 0)
);

CREATE TABLE ArtículoLugar (
    ID_Artículo INT NOT NULL 
		CONSTRAINT ARTICULO_LUGAR_ID_ARTICULO_FK 
        	REFERENCES Artículo(ID_Artículo) ON DELETE CASCADE ON UPDATE CASCADE,
    ID_Lugar INT NOT NULL 
		CONSTRAINT ARTICULO_LUGAR_ID_LUGAR_FK 
        	REFERENCES Lugar(ID_Lugar) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT ARTICULOLUGAR_ID_ARTICULO_LUGAR_PK 
		PRIMARY KEY(id_lugar,"id_artículo")
);

CREATE TABLE Evento (
    ID_Evento SERIAL NOT NULL 
		CONSTRAINT EVENTO_ID_EVENTO_PK PRIMARY KEY,
    Nombre VARCHAR(55) NOT NULL,
    Descripción TEXT
);

CREATE TABLE EventoLugar (
    ID_Evento INT NOT NULL 
		CONSTRAINT EVENTO_LUGAR_ID_EVENTO_FK 
        	REFERENCES Evento(ID_Evento) ON DELETE CASCADE ON UPDATE CASCADE,
    ID_Lugar INT NOT NULL 
		CONSTRAINT EVENTO_LUGAR_ID_LUGAR_FK 
        	REFERENCES Lugar(ID_Lugar) ON DELETE CASCADE ON UPDATE CASCADE,
    Fecha DATE NOT NULL,
    	CONSTRAINT UNQ_EVENTO_LUGAR UNIQUE (ID_Lugar, Fecha),
	CONSTRAINT EVENTOLUGAR_ID_EVENTO_LUGAR_PK 
		PRIMARY KEY(id_evento,id_lugar)
);

ALTER TABLE usuario
ADD COLUMN rol VARCHAR(5)
	CONSTRAINT USUARIO_ROL_DF DEFAULT 'USER'
	CONSTRAINT USUARIO_ROL_CK CHECK(rol IN ('ADMIN', 'USER'))
